server.port=8082

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
#spring.http.multipart.max-file-size=100MB
#spring.http.multipart.max-request-size=100MB
#spring.http.multipart.location=/Users/sbattjer/workspace/opsware/uploadDir
spring.http.multipart.location=C:/workspace/uploadDir
#spring.http.multipart.location=/opt/conformance/uploads
server.connection-timeout=50s
server.tomcat.max-http-post-size=100000000


show.debug=false
validate.schema=true
#schema.location=/Users/sbattjer/workspace/opsware/bsil-ebts-conformance/src/main/resources/ebts/xsd/dod_ebts/4.1/dod_ebts.xsd
#schema.location=C:/workspace/bsil-ebts-conformance/src/main/resources/ebts/xsd/dod_ebts/4.1/dod_ebts.xsd
#schema.location=C:/workspace/ebts/xsd/dod_ebts/4.1/dod_ebts.xsd
schema.location=C:/workspace/bsil-ebts-conformance/src/main/resources/schemas/
#schema.location=/opt/conformance/xsd/dod_ebts/4.1/dod_ebts.xsd
save.binary=false
#binary.output=/Users/sbattjer/Downloads/4.1_binaries/
binary.output=/opt/conformance/binaries